version: '3.5'

services:

  eosio:
    container_name: devnode_eosio
    build:
      context: ./services/eosio
      dockerfile: Dockerfile
    image: devnode/eosio
    ports:
      - '8888:8888'
      - '9831:9876'
    environment:
      DATA_DIR: /root/data-dir
      CONFIG_DIR: /opt/application/config
    volumes:
      - ./services/eosio/data:/root/data-dir
      - ./services/eosio:/opt/application
      
networks:
  default:
    name: devnode
