version: '3.5'

services:

  eosio:
    container_name: tykhon_eosio
    build:
      context: ./services/eosio
      dockerfile: Dockerfile
    image: tykhon/eosio
    ports:
      - '8888:8888'
      - '9831:9876'
    environment:
      DATA_DIR: /root/data-dir
      CONFIG_DIR: /opt/application/config
    volumes:
      - eosio_data:/root/data-dir
      - ./services/eosio:/opt/application

volumes:
  eosio_data:

networks:
  default:
    name: tykhon
